inherit_from:
  - .rubocop_todo.yml
  - https://raw.githubusercontent.com/riboseinc/oss-guides/main/ci/rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: false

plugins:
  - rubocop-performance