inherit_from:
  - 'https://raw.githubusercontent.com/fontist/oss-guides/master/ci/rubocop.yml'

AllCops:
  Exclude:
    - 'lib/fontist/import/google/fonts_public.pb.rb'
    - 'lib/fontist/formula_template.rb'

Rails:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - 'lib/fontist/formulas/**/*.rb'

Layout/IndentFirstHashElement:
  Exclude:
    - 'lib/fontist/formulas/**/*.rb'

Layout/IndentHeredoc:
  Exclude:
    - 'lib/fontist/formulas/**/*.rb'
