require_relative "extractors/extractor"
require_relative "extractors/zip_extractor"
require_relative "extractors/ole_extractor"
require_relative "extractors/seven_zip_extractor"
require_relative "extractors/cab_extractor"
