name: check_google

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install bundler
        run: gem install bundler

      - name: Setup
        run: bin/setup

      - name: Check new fonts
        run: bin/check_google
