name: macos

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install otfinfo
        run: brew install lcdf-typetools

      - name: Install bundler
        run: gem install bundler

      - name: Setup
        run: bin/setup

      - name: Run tests
        run: TEST_ENV=CI bin/rspec
