name: metanorma

on:
  push:
    # restore the main branch after metanorma upgrade
    # branches: [ main ]
    branches: [ unknown ]
  # restore after metanorma upgrade
  # pull_request:

jobs:
  test:
    name: Test on Ruby ${{ matrix.ruby }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.5', '2.6', '2.7', '3.0' ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        experimental: [ true ]
    steps:
      - uses: actions/checkout@master
        with:
          repository: metanorma/metanorma

      - uses: actions/checkout@master
        with:
          path: "fontist"

      - run: 'echo ''gem "fontist", path: "./fontist"'' > Gemfile.devel'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rake
