name: rake-metanorma

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.ref_name }}'
  cancel-in-progress: true

env:
  BUNDLER_VER: latest

jobs:
  prepare:
    # commented for https://github.com/fontist/fontist/issues/428#issuecomment-3992198584
    uses: metanorma/ci/.github/workflows/prepare-rake.yml@main

  metanorma:
    name: Test metanorma on Ruby ${{ matrix.ruby.version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    needs: prepare
    if: needs.prepare.outputs.push-for-tag != 'true'

    continue-on-error: ${{ matrix.ruby.experimental }}
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v6
        with:
          repository: metanorma/metanorma

      - uses: actions/checkout@v6
        with:
          path: "fontist"

      - run: 'echo ''gem "fontist", path: "./fontist"'' > Gemfile.devel'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.version }}
          rubygems: ${{ matrix.ruby.rubygems }}
          bundler: ${{ env.BUNDLER_VER }}
          bundler-cache: true

      - uses: metanorma/ci/inkscape-setup-action@main

      - name: Configure Git credentials
        env:
          GIT_TOKEN: ${{ secrets.FONTIST_CI_PAT_TOKEN }}
        run: |
          git config --global user.name 'Fontist CI'
          git config --global user.email 'fontist@ribose.com'
          git config --global credential.helper store
          echo "https://fontist-ci:${GIT_TOKEN}@github.com" > ~/.git-credentials
        shell: bash

      - run: |
          bundle exec fontist update
          bundle exec fontist repo setup metanorma https://github.com/metanorma/fontist-formulas-private.git
          bundle exec fontist repo update metanorma
        shell: bash

      - run: bundle exec rake
        shell: bash
