name: rake-metanorma

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.ref_name }}'
  cancel-in-progress: true

env:
  BUNDLER_VER: latest

jobs:
  clone_formulas:
    name: Clone formulas repo
    runs-on: ${{ matrix.os }}
    steps:
      - if: startsWith(matrix.os, 'windows')
        name: Pre-clone formulas repo on Windows
        run: |
          git clone --branch v4 --depth 1 https://github.com/fontist/formulas.git C:\temp\fontist\versions\v4\formulas
        shell: powershell

  prepare:
    needs: clone_formulas
    uses: metanorma/ci/.github/workflows/inkscape-rake.yml@main
    # uses: metanorma/ci/.github/workflows/prepare-rake.yml@main commented for https://github.com/fontist/fontist/issues/428#issuecomment-3992198584

  metanorma:
    name: Test metanorma on Ruby ${{ matrix.ruby.version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    needs: prepare
    if: needs.prepare.outputs.push-for-tag != 'true'

    continue-on-error: ${{ matrix.ruby.experimental }}
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4
        with:
          repository: metanorma/metanorma

      - uses: actions/checkout@master
        with:
          path: "fontist"

      - run: 'echo ''gem "fontist", path: "./fontist"'' > Gemfile.devel'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.version }}
          rubygems: ${{ matrix.ruby.rubygems }}
          bundler: ${{ env.BUNDLER_VER }}
          bundler-cache: true

      # - uses: metanorma/metanorma-build-scripts/inkscape-setup-action@main

      - run: bundle exec rake

