name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
          architecture: 'x64'

      - run: bundle config set path 'vendor/bundle'

      - run: bundle install --jobs 4 --retry 3

      - run: bundle exec rspec --tag ~dev
        env:
          TEST_ENV: CI

      - name: Publish to rubygems.org
        env:
          RUBYGEMS_API_KEY: ${{secrets.FONTIST_CI_RUBYGEMS_API_KEY}}
        run: |
          gem install gem-release
          touch ~/.gem/credentials
          cat > ~/.gem/credentials << EOF
          ---
          :rubygems_api_key: ${RUBYGEMS_API_KEY}
          EOF
          chmod 0600 ~/.gem/credentials
          git status
          gem release

